# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
sudo: true
osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
install:
  - cd Example/
  - pod update
  - cd ../
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/LJCollapseLabel.xcworkspace -scheme LJCollapseLabel-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

